import time
from selenium import webdriver
from selenium.webdriver.common.by import By

# driver = webdriver.Chrome()
# driver.get("https://www.facebook.com/")
# txtusername = driver.find_element(By.ID, "email")
# txtusername.send_keys("shalini")
# txtpassword = driver.find_element(By.ID, "pass")
# txtpassword.send_keys("Thiya")
# time.sleep(6)

# driver = webdriver.Chrome()
# driver.get("https://www.google.com/")
# searchbox = driver.find_element(By.CLASS_NAME, "gLFyf")
# searchbox.send_keys("Apple phone")
# time.sleep(5)
#
# driver = webdriver.Chrome()
# driver.get("https://netbanking.hdfcbank.com/netbanking/")
# driver.implicitly_wait(5)
# driver.switch_to.frame("login_page")
# customerid = driver.find_element(By.NAME, "fldLoginUserId")
# # customerid = driver.find_element(By.XPATH, "//input[@type='text']")
# customerid.send_keys("Shalini")
# # print(driver.find_element(By.XPATH,"//div[text()='Login to NetBanking']").text)
#
# time.sleep(5)

# driver = webdriver.Chrome()
# driver.get("https://www.swiggy.com/")
# #locationadd = driver.find_element(By.ID, "location")
# locationadd = driver.find_element(By.XPATH, "//input[@type='text']")
# locationadd.send_keys("Chennai")
# time.sleep(6)

# driver = webdriver.Chrome()
# driver.get("https://www.snapdeal.com/login")
# #mobileno = driver.find_element(By.XPATH, "//input[@type='text']")
# mobileno = driver.find_element(By.ID, "userName")
# mobileno.send_keys("6383585128")
# time.sleep(5)

# driver = webdriver.Chrome()
# #driver.get("https://www.instagram.com/accounts/login/?hl=en) login page")
# driver.get("https://www.instagram.com/accounts/login/?hl=en)%20login%20page")
# phoneno = driver.find_element(By.XPATH, "//input[@type='text']")
# phoneno.send_keys("6383585128")
# password = driver.find_element(By.XPATH, "//input[@type='password']")
# password.send_keys("Thiya")
# time.sleep(6)

# driver = webdriver.Chrome()
# driver.get("https://www.irctc.co.in/")
# time.sleep(5)
# okbtn = driver.find_element(By.XPATH, "//button[text()='OK']")
# okbtn.click()
# fromadd = driver.find_element(By.XPATH, "//p-autocomplete[@id='origin']//input")
# #fromadd = driver.find_element(By.XPATH, "(//input[@role='searchbox'])[0]")
# fromadd.send_keys("Chennai")# toadd = driver.find_element(By.XPATH, "(//input[@type='text'])[1]")
# toadd = driver.find_element(By.XPATH, "//p-autocomplete[@id='destination']//input")
# toadd.send_keys("Bangalore")
# time.sleep(5)

import time
from selenium import webdriver
from selenium.webdriver.common.by import By
driver = webdriver.Chrome()
driver.get("https://adactinhotelapp.com/")
driver.implicitly_wait(10)
username = driver.find_element(By.ID, "username")
#username = driver.find_element(By.NAME, "username")
#username = driver.find_element(By.XPATH, "//input[@id='username']")
#username.send_keys("Shalini")
driver.execute_script("arguments[0].setAttribute('value','Chennai')",username)
#password = driver.find_element(By.ID, "password")
password = driver.find_element(By.NAME, "password")
#password = driver.find_element(By.XPATH, "//input[@type='password']")
password.send_keys("12345")
time.sleep(6)

# driver = webdriver.Chrome()
# driver.get("https://www.redbus.in/")
# driver.implicitly_wait(10)
# fromadd = driver.find_element(By.XPATH, "//div[text()='From']")
# fromadd.click()
# time.sleep(2)
# # fromadd.send_keys("Chennai")
# driver.find_element(By.ID,"srcDest").send_keys("Chennai")
# # driver.execute_script("arguments[0].setAttribute('value','Chennai')",fromadd)
##########(//div[@class='searchCategory___03761b'])[1]//div[contains(@class,'listHeader')]
# toadd = driver.find_element(By.XPATH, "//div[text()='To']")
# toadd.click()
# driver.find_element(By.ID,"srcDest").send_keys("Bangalore")
# time.sleep(2)
# # toadd.send_keys("Bangalore")
# # driver.execute_script("arguments[0].setAttribute('value','Bangalore')",toadd)
# time.sleep(6)

# driver = webdriver.Chrome()
# driver.get("https://infinitynxt.icicibank.com/in/login-page")
# #userid = driver.find_element(By.XPATH, "(//input[@type='text'])[0]")
# #userid = driver.find_element(By.XPATH, "//label[text()='User ID']")
# userid = driver.find_element(By.ID, "user-id")
# userid.send_keys("Shalini")
# #password = driver.find_element(By.XPATH, "//input[@type='password']")
# #password = driver.find_element(By.XPATH, "//label[text()='Password']")
# password = driver.find_element(By.ID, "password")
# #password = driver.find_element(By.NAME, "password-l")
# password.send_keys("12345")
# time.sleep(5)

