from selenium import webdriver
from selenium.webdriver import ActionChains
from selenium.webdriver.common.by import By
import time
from selenium.webdriver.support.select import Select
# driver = webdriver.Chrome()
# driver.get("https://www.greenstechnologys.com/")
# contactus = driver.find_element(By.XPATH, "//a[text()='CONTACT US']")
# contactus.click()
# a=ActionChains(driver)
# name = driver.find_element(By.ID, "InputName")
# a.move_to_element(name).perform()
# name.send_keys("shalini")
# email = driver.find_element(By.ID, "InputEmail1")
# a.move_to_element(email).perform()
# email.send_keys("shaluyalini@gmail.com")
# mobile = driver.find_element(By.ID, "InputSubject")
# a.move_to_element(mobile).perform()
# mobile.send_keys("9600960891")
# course = driver.find_element(By.XPATH, "//select[@name='courses']")
# s=Select(course)
# s.select_by_index(6)
# branch = driver.find_element(By.XPATH, "//select[@name='branch']")
# s=Select(branch)
# #s.select_by_visible_text("Tambaram")
# s.select_by_value("Tambaram")
# plan = driver.find_element(By.NAME, "time")
# s=Select(plan)
# s.select_by_visible_text("Immediately")
# message = driver.find_element(By.NAME, "comments")
# message.send_keys("No comments")
# submit = driver.find_element(By.ID, "submit")
# submit.click()
# time.sleep(6)

# driver = webdriver.Chrome()
# driver.get("https://www.facebook.com/")
# createnewacc =driver.find_element(By.XPATH, "(//a[@role='button'])[2]")
# createnewacc.click()
# firstname = driver.find_element(By.XPATH, "(//input[@type='text'])[1]")
# firstname.send_keys("shalini")
# surname = driver.find_element(By.XPATH, "(//input[@type='text'])[2]")
# surname.send_keys("siva")
# datedrp = driver.find_element(By.ID, "day")
# s=Select(datedrp)
# s.select_by_value("9")
# monthdrp = driver.find_element(By.ID, "month")
# s=Select(monthdrp)
# s.select_by_visible_text("Jan")
# yeardrp = driver.find_element(By.ID, "year")
# s=Select(yeardrp)
# s.select_by_visible_text("2000")
# genderbutton = driver.find_element(By.ID, "sex")
# genderbutton.click()
# mobilenumber = driver.find_element(By.XPATH, "(//input[@type='text'])[5]")
# mobilenumber.send_keys("9095897199")
# password = driver.find_element(By.ID, "password_step_input")
# password.send_keys("123456789")
# signup = driver.find_element(By.NAME, "websubmit")
# signup.click()
# time.sleep(5)

# driver = webdriver.Chrome()
# driver.get("https://demo.automationtesting.in/Register.html")
# firstname = driver.find_element(By.XPATH, "(//input[@type='text'])[1]")
# firstname.send_keys("shalini")
# lastname = driver.find_element(By.XPATH, "(//input[@type='text'])[2]")
# lastname.send_keys("siva")
# address = driver.find_element(By.XPATH, "//textarea[@rows='3']")
# address.send_keys("Chennai")
# email = driver.find_element(By.XPATH, "//input[@type='email']")
# email.send_keys("shaluyalini@gmail.com")
# phone = driver.find_element(By.XPATH, "//input[@type='tel']")
# phone.send_keys("0123456789")
# genderbutton = driver.find_element(By.XPATH, "(//input[@type='radio'])[2]")
# genderbutton.click()
# hobbies = driver.find_element(By.ID, "checkbox2")
# hobbies.click()
# hobbies2 = driver.find_element(By.ID, "checkbox1")
# hobbies2.click()
# driver.find_element(By.ID, "msdd").click()
# languages = driver.find_element(By.XPATH, "//a[text()='English']")
# lang=languages.text
# print(lang)
# languages.click()
# time.sleep(3)
# skills = driver.find_element(By.XPATH, "(//select[@type='text'])[1]")
# s=Select(skills)
# s.select_by_value("Engineering")
# # country = driver.find_element(By.XPATH, "(//select[@type='text'])[2]")
# # country.click()
# # s=Select(country)
# # s.select_by_visible_text("Select Country")
# selectcountry = driver.find_element(By.XPATH,"//span[@role='combobox']")
# selectcountry.click()
# india = driver.find_element(By.XPATH,"//li[text()='India']")
# india.click()
# time.sleep(3)
# year = driver.find_element(By.XPATH, "(//select[@type='text'])[3]")
# s=Select(year)
# s.select_by_value("2000")
# month = driver.find_element(By.XPATH, "(//select[@type='text'])[4]")
# s=Select(month)
# s.select_by_value("January")
# day = driver.find_element(By.XPATH, "(//select[@type='text'])[5]")
# s=Select(day)
# s.select_by_value("9")
# password = driver.find_element(By.ID, "firstpassword")
# password.send_keys("12345")
# cnfrmpassword = driver.find_element(By.ID, "secondpassword")
# cnfrmpassword.send_keys("12345")
# submitbtn = driver.find_element(By.ID, "submitbtn")
# submitbtn.click()
# time.sleep(4)

# driver = webdriver.Chrome()
# driver.get("https://greenstech.in/selenium-course-content.html")
# a=ActionChains(driver)
# interviewqn = driver.find_element(By.ID, "heading20")
# a.move_to_element(interviewqn).perform()
# interviewqn.click()
# cts = driver.find_element(By.XPATH, "//a[text()='CTS Interview Question ']")
# a.move_to_element(cts).perform()
# cts.click()
# time.sleep(3)

# driver = webdriver.Chrome()
# driver.get("https://www.cleartrip.com/trains")
# fromadd = driver.find_element(By.XPATH, "(//input[@type='text'])[1]")
# fromadd.send_keys("Chennai")
# toadd = driver.find_element(By.XPATH, "(//input[@type='text'])[2]")
# toadd.send_keys("Bangalore")
# date = driver.find_element(By.XPATH, "(//input[@type='text'])[3]")
# date.clear()
# date.send_keys("10/10/2025")
# adults = driver.find_element(By.NAME, "adults")
# s=Select(adults)
# s.select_by_value("2")
# childrencount = driver.find_element(By.NAME, "children")
# s=Select(childrencount)
# s.select_by_value("1")
# seniormen = driver.find_element(By.XPATH, "(//select[@size='1'])[3]")
# s=Select(seniormen)
# s.select_by_value("1")
# seniorwomen = driver.find_element(By.XPATH, "(//select[@size='1'])[4]")
# s=Select(seniorwomen)
# s.select_by_value("1")
# srchbtn = driver.find_element(By.ID, "trainFormButton")
# srchbtn.click()
# time.sleep(4)

# driver = webdriver.Chrome()
# driver.get("https://greenstech.in/selenium-course-content.html")
# a=ActionChains(driver)
# softwarelink = driver.find_element(By.XPATH, "//h2[contains(text(),'Software')]")
# a.move_to_element(softwarelink).perform()
# softwarelink.click()
# corejava = driver.find_element(By.XPATH, "//a[text()='Core JAVA  material']")
# a.move_to_element(corejava).perform()
# corejava.click()
# time.sleep(3)

# driver = webdriver.Chrome()
# driver.get("https://www.flipkart.com/")
# a = ActionChains(driver)
# login = driver.find_element(By.XPATH, "//span[text()='Login']")
# signup = driver.find_element(By.XPATH, "//span[text()='Sign Up']")
# a.move_to_element(login).move_to_element(signup).click().perform()
# mobnumber = driver.find_element(By.XPATH, "(//input[@type='text'])[2]")
# mobnumber.send_keys("9876543210")
# continuebtn = driver.find_element(By.XPATH, "(//button[@type='submit'])[2]")
# continuebtn.click()
# time.sleep(4)

# driver = webdriver.Chrome()
# driver.get("https://www.amazon.in/")
# a = ActionChains(driver)
# signin = driver.find_element(By.XPATH, "//span[text()='Hello, sign in']")
# signin1 = driver.find_element(By.XPATH, "//span[text()='Sign in'][1]")
# a.move_to_element(signin).move_to_element(signin1).click().perform()
# mobnumber = driver.find_element(By.NAME, "email")
# mobnumber.send_keys("9876543210")
# continuebtn = driver.find_element(By.ID, "continue")
# continuebtn.click()
# time.sleep(4)

driver = webdriver.Chrome()
driver.get("https://accounts.google.com/signup/v2/webcreateaccount?hl=en&flowName=GlifWebSignIn&flowEntry=SignUp")
driver.implicitly_wait(10)
firstname = driver.find_element(By.ID,"firstName")
firstname.send_keys("shalini")
lastname = driver.find_element(By.ID,"lastName")
lastname.send_keys("siva")
nxtbtn = driver.find_element(By.XPATH, "//span[text()='Next']")
nxtbtn.click()
# month = driver.find_element(By.XPATH, "(//div[@class='VfPpkd-aPP78e'])[1]")
# month.click()
# january = driver.find_element(By.XPATH,"//li[@role='option']//span[text()='January']")
# january.click()
# day = driver.find_element(By.ID,"day")
# day.click()
# day.send_keys("9")
# year = driver.find_element(By.ID,"year")
# year.click()
# year.send_keys("2000")
driver.find_element(By.XPATH,"(//span[@class='VfPpkd-NSFCdd-Ra9xwd'])[1]").click()
driver.find_element(By.XPATH,"//span[text()='January']").click()

# gender = driver.find_element(By.XPATH,"(//div[@class='VfPpkd-aPP78e'])[2]")
# gender.click()
# female = driver.find_element(By.XPATH, "(//li[@role='option']//span[text()='Female'])[1]")
# female.click()
time.sleep(3)

# driver = webdriver.Chrome()
# driver.get("https://www.irctc.co.in/")
# time.sleep(5)
# okbtn = driver.find_element(By.XPATH, "//button[text()='OK']")
# okbtn.click()
# register = driver.find_element(By.XPATH, "//a[text()=' REGISTER ']")
# register.click()
